### ISSUE TITLE
Design todo list

### ISSUE THREAD

**Issue by matthewcarleton** [rhdemo/2021-frontend-css-html#2]
- [x] Create all ship illustrations @andrew-ronaldson 
- [x] create sunken version of each ship
- [x] Create enemy board pegs @andrew-ronaldson 
- [x] Create Ropes @andrew-ronaldson 
- [x] Create bouys @andrew-ronaldson 
- [x] Create ship views for bonus round @andrew-ronaldson 
- [x] Complete UI for top ten @matthewcarleton 
- [x] Complete UI for game data @matthewcarleton 
- [x] Complete UI for actions @matthewcarleton 
- [x] Complete UI for countdown @matthewcarleton 
- [x] Create more avatars @matthewcarleton / @andrew-ronaldson / @lizsurette 
- [x] Bonus round designs @andrew-ronaldson / @matthewcarleton 
- [x] Fires (animations) @andrew-ronaldson 
- [x] Dashboard @matthewcarleton 
- [x] build everything @matthewcarleton 
- [ ] Heat map
- [x] Rotate button
- [x] Explosion animation (bonus round)
